### PR TITLE
Update protobuf to v6 to resolve npm security warning

### PR DESCRIPTION
**Pull request by feross**
I need help confirming that this PR works as intended. I do not have a chromecast handy at the moment.

### CODE REVIEW

**Comment by dsteinman** [comment]
I tried it out on my code but looks like one of the parameters to protobuf is missing:

```
device: Device {
  id: '77b3f60a97fd61a1c7a1fed0067a4935',
  name: 'Family room TV',
  host: '192.168.1.226',
  port: 8009,
  type: 'Chromecast' }
Scanner - found device Family room TV (Chromecast) at 192.168.1.226:8009
MediaPlayer - New device Family room TV at 192.168.1.226:8009
buffer.js:508
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:508:11)
    at BufferWriter.write_string_buffer [as string] (chromecast-plugin/node_modules/castv2/node_modules/protobufjs/src/writer_buffer.js:68:22)
    at Type.CastMessage$encode [as encode] (eval at Codegen (chromecast-plugin/node_modules/castv2/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:7:16)
    at Type.encode_setup [as encode] (chromecast-plugin/node_modules/castv2/node_modules/protobufjs/src/type.js:485:25)
    at Object.serialize (chromecast-plugin/node_modules/castv2/lib/proto.js:32:22)
    at Client.send (chromecast-plugin/node_modules/castv2/lib/client.js:127:25)
    at Channel.send (chromecast-plugin/node_modules/castv2/lib/channel.js:34:12)
    at fn.Controller.send (chromecast-plugin/node_modules/castv2-client/lib/controllers/controller.js:28:16)
    at fn.ConnectionController.connect (chromecast-plugin/node_modules/castv2-client/lib/controllers/connection.js:28:8)
    at Client.<anonymous> (chromecast-plugin/node_modules/castv2-client/lib/senders/platform.js:59:21)
```

**Comment by feross** [comment]
@dsteinman Can you run the code again, but enable the debug logs this time?

Just run your script with the `DEBUG` environment variable set as follows:

```js
DEBUG='castv2' node your-script.js
```

**Comment by dsteinman** [comment]
The only difference is these additional debug lines from right before that error.

```
  castv2 connecting to 192.168.1.226:8009 ... +0ms
  castv2 connected +480ms
  castv2 send message: protocolVersion=0 sourceId=sender-0 destinationId=receiver-0 namespace=urn:x-cast:com.google.cast.tp.connection data={"type":"CONNECT"} +1ms
```

**Comment by feross** [comment]
@dsteinman Thank you. That was very helpful. I just made some changes that should fix the problem. Can you try again once more?

**Comment by dsteinman** [comment]
Looks like that might be working, but I can't 100% confirm because the rest of my code no longer works :/

```
PersistentClient - Family room TV - Connected client
PersistentPlayer - Family room TV - Try to join player
PersistentPlayer - Family room TV - Connected player
PersistentPlayer - Family room TV - Player joint
```

Looks okay and no errors.  But `castService.connect(device, callback)` does not call the callback after what looks like a successful connection.  And this now happens on the master branch too.  So it might be something else, or maybe my Chromecast needs an update.  I'll check back if I get it working.

**Comment by vincentcr** [comment]
Hi @feross I just tried this PR with my code (via https://github.com/thibauts/node-castv2-client), and it works just like before. So LGTM!

**Comment by vincentcr** [comment]
@feross please let me know if there are specific checks or tests you'd like me to do.

**Comment by feross** [comment]
@vincentcr This is good enough for me. I'll merge and release a new version.

**Comment by feross** [comment]
Released castv2@0.1.10.

**Comment by vincentcr** [comment]
Awesome, thanks @feross

**Pull request merged**
